export enum Permission {
  VIEW_DASHBOARD = 'canViewDashboard',
  VIEW_SKILLS = 'canViewSkills',
  EDIT_OWN_SKILLS = 'canEditOwnSkills',
  EDIT_TEAM_SKILLS = 'canEditTeamSkills',
  EDIT_ALL_SKILLS = 'canEditAllSkills',
  VIEW_LEARNING = 'canViewLearning',
  EDIT_OWN_LEARNING = 'canEditOwnLearning',
  EDIT_TEAM_LEARNING = 'canEditTeamLearning',
  EDIT_ALL_LEARNING = 'canEditAllLearning',
  VIEW_REPORTS = 'canViewReports',
  MANAGE_TEAM = 'canManageTeam',
  MANAGE_SYSTEM = 'canManageSystem',
  MANAGE_USERS = 'canManageUsers',
}
