global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user_service'
    static_configs:
      - targets: ['172.31.220.111:3001']
  - job_name: 'skills_service'
    static_configs:
      - targets: ['172.31.220.111:3002']
  - job_name: 'learning_service'
    static_configs:
      - targets: ['172.31.220.111:3003']
  - job_name: 'email_service'
    static_configs:
      - targets: ['172.31.220.111:3005']
  - job_name: 'event_processes_service'
    static_configs:
      - targets: ['172.31.220.111:3006']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
