apiVersion: 1
groups:
    - orgId: 1
      name: application_metrics
      folder: skills_base_metrics
      interval: 10s
      rules:
        - uid: de3vzibfj82yoa
          title: HTTP Error Rate High
          condition: A
          data:
            - refId: A
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: "sum(rate(user_service_http_requests_total{status=~\"4.*\"}[1m])) \n      / \n      sum(rate(user_service_http_requests_total[5m])) * 100"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 10s
          annotations:
            description: High Error Rate
            summary: High Error Rate
          isPaused: false
          notification_settings:
            receiver: skills_base_email_service
